= matrix-access-limit-spring-boot-starter
Doc Writer <spring-boot@qq.com>
:icons: font
:toc: right
:pdf-themesdir: theme
:pdf-fontsdir: font
:pdf-theme: KaiGenGothicCN
:homepage: https://github.com/miverse/matrix-boot
:sourcedir: matrix-access-limit-spring-boot-starter/src/main/java/com/matrixboot/access/limit
:assetsdir: assets
:imagesdir: {assetsdir}/images
:revnumber: 0.0.1-SNAPSHOT
:revdate: 2022-01-11

== 简介

****

在某些场景下,某一用户在固定的时间内只允许请求固定次数, 如: 请求短信验证码.
matrix-access-limit-spring-boot-starter 主要用于请求次数的限制, 未接入风控之前可以使用这个包解决一部分问题.

****

== 快速使用

在 POM 中添加下列依赖

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>com.matrixboot</groupId>
    <artifactId>matrix-access-limit-spring-boot-starter</artifactId>
    <version>{revnumber}</version>
</dependency>
----

== 注解介绍

|===
|注解 |说明 |示例

|`@AccessLimit`
|对单个字段进行了请求限制
|`@AccessLimit("#queryData.username")`

|`@AccessLimits`
|对多个字段进行了请求限制
|`@AccessLimits({@AccessLimit, @AccessLimit})`
|===

== 编写代码

定义一个方法参数: QueryData

[source,java]
----
@Data
public class QueryData {
    private String group;
    private String username;
    private String note;
}
----

=== 方法 1

[source,java]
----
@RestController
public class AccessLimitFacade {

    @AccessLimit("#queryData.username") // <!--1-->
    @GetMapping("example1")
    public QueryData example1(QueryData queryData) {
        return queryData;
    }
}
----

<1> 表示对方法参数 `queryData.username` 字段请求次数进行限制,

[TIP]
.提示
====
. `#queryData.username` 中的 # 表示从方法参数中取对应的字段,
====

=== 方法 2

定义一个类加入到 Spring 容器中,并命名为 `ConverterService`

[source,java]
----
@Service("ConverterService")
public class DataConverterService {
    public String check(@NotNull QueryData queryData) {
        return queryData.getGroup() + ":" + queryData.getUsername();
    }
}
----

[source,java]
----
@RestController
public class AccessLimitFacade {

    @AccessLimit("@ConverterService.check(#queryData)") // <!--1-->
    @GetMapping("example2")
    public QueryData example2(QueryData queryData) {
        return queryData;
    }
}
----

<1> 表示使用 ConverterService.check 方法对参数进行转换,

[TIP]
.提示
====
. `@ConverterService.check(#queryData)` 中的 @ 表示从spring 容器中取出命名为 ConverterService 的对象进行处理
====

=== 方法 3

[source,java]
----
@RestController
public class AccessLimitFacade {
    @AccessLimits({  //<!--1-->
            @AccessLimit(value = "#queryData.username", times = 2, message = "用户名请求次数超过了限制!"),//<!--2-->
            @AccessLimit(value = "#queryData.group", times = 4, message = "用户组请求次数超过了限制!")    //<!--3-->
    })
    @GetMapping("example3")
    public QueryData example3(QueryData queryData) {
        return queryData;
    }
}
----

<1> 使用了组合限制注解
<2> 对用户名限制
<3> 对用户组限制

=== 方法 4

[source,java]
----
@RestController
public class AccessLimitFacade {

    @AccessLimit(value = "#queryData.username", message = "用户名请求次数超过了限制!", times = 4, timeout = 30, reveal = "reveal")//<!--1-->
    @GetMapping("example4")
    public QueryData example4(QueryData queryData) {
        return queryData;
    }

    @SuppressWarnings("unused")
    public QueryData reveal(QueryData queryData, AccessLimitException exception) {//<!--2-->
        return new QueryData();
    }
}
----

<1> 可以指定方法参数
<2> 当发生限制时, 指定了回调函数,可以传入异常类

== 参数描述

|===
^|字段 ^|描述 ^|类型 ^|示例

|value
|指定方法参数作为 key,支持 SPEL 表达式格式
|String
|`#queryData.username` `@ConverterService.check(#queryData)`

|message
|提示信息
|String
|用户名请求次数超过了限制!

|times
|限制的次数,默认是 3
|int
|3

|timeout
|限制次数时间窗口,这里是翻转时间窗口,默认是 60 秒
|int
|60

|reveal
|触发了限制次数时回调的方法,这里是方法名称,方法参数最好是和之前的参数一样,获取异常信息可以在方法参数加上 `AccessLimitException`
|String
|reveal
|===









