POST http://localhost:8080/user1
Content-Type: application/json

{
  "username": "username1",
  "mobile": "18812341234"
}

###
POST http://localhost:8080/user2
Content-Type: application/json

{
  "username": "username1",
  "mobile": "18812341234"
}

###
