---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shishaodong.
--- DateTime: 2022/1/12 2:59 PM
---

local result = redis.call("EXISTS", KEYS[1]);
if result == 1 then
    redis.call("DEL", KEYS[1])
    return 1
end
return 0



