GET http://localhost:8080/example1?username=123
Accept: application/json

###

GET http://localhost:8080/example2?username=123&group=test
Accept: application/json


###
GET http://localhost:8080/example3?username=345&group=test123
Accept: application/json

###


